import React from 'react'
import Successful from '../../components/payments/Successful'
import Head from 'next/head'
import * as cookie from 'cookie'
import axios from 'axios'
import Router from 'next/router'
import {BaseUrl} from "../../components/baseUrl/BaseUrl";



const successful = ({data}) => {
  data === false && Router.push("/")
  return (
    <div>
        <Head>
        <title>پرداخت موفق | وتنا</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Successful data={data}/>
    </div>
  )
}

export async function getServerSideProps(context){
  
  let resault = null;

  const queryParams = new URLSearchParams(context.query);
  const order_id = queryParams.get('tc');

  const parsedCookies = cookie.parse(context.req.headers.cookie);
  const data = await axios.post(encodeURI(`${BaseUrl}/verify_for_cart/`), {
    tracking_code :order_id
  } ,{
    headers:{
      'Authorization': 'Token '+ parsedCookies.token, 
  },
  }).then(response => {
    if (response) {
      resault = true;
    }
  }).catch(err => {
    resault = false;
  })
  

  return{
    props:{data: resault}
  }
}

export default successful